version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    networks:
      - proxy
      - internal
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    # THESE CAN BE USED TO AUTOCONFIGURE IF BUILDING FROM SCRATCH
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=xxxxxxxxxx
      - MYSQL_DATABASE=nextcloud
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_ADMIN_USER=xxxxxxxxx
      - NEXTCLOUD_ADMIN_PASSWORD=xxxxxxxxxx
      - NEXTCLOUD_TRUSTED_DOMAINS= cloud.youdomain.com 192.168.10.0/24 #These are the networks you will be able to access nextcloud from, edit them according to your setup
      - TRUSTED_PROXIES=192.168.10.20
    volumes:
      - /srv/dev-disk-by-label-media/Files/AppData/nextcloud/config:/var/www/html/config
      - /srv/dev-disk-by-label-media/Files/AppData/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - /srv/dev-disk-by-label-tank/nextcloud/data:/var/www/html/data #This is where all the file that you upload are saved, you can edit to any location you like.
      - /srv/dev-disk-by-label-media/Files/AppData/nextcloud/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8443:443" #8443 must be available, you can replace it with anything you like as long as it is not being used elsewhere

  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    # Replace the password
    command: ["redis-server", "--requirepass", "xxxxxxxxxx", "--appendonly", "yes"]
    restart: always
    networks:
      - internal

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=mysqld-bin --binlog-format=ROW --innodb=on
    # THESE CAN BE USED TO AUTOCONFIGURE IF BUILDING FROM SCRATCH
    environment:
     - MYSQL_ROOT_PASSWORD=XXXXXXXXXXXXX
     - MYSQL_USER=nextcloud
     - MYSQL_PASSWORD=XXXXXXXXXXXX
     - MYSQL_DATABASE=nextcloud
    networks:
      - internal
    volumes:
      - /srv/dev-disk-by-label-media/Files/AppData/nextcloud/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
